python -m experiments.exp_ir_study_base_psi --do
python -m experiments.exp_ir_study_base_psi_asset_i --do 
python -m experiments.exp_ir_study_base_psi_asset_i_canary --do
python -m experiments.exp_ir_study_base_psi_asset_i1 --do 
python -m experiments.exp_ir_study_base_psi_asset_j --do 
python -m experiments.exp_ir_study_base_psi_asset_j1 --do 
python -m experiments.exp_ir_study_base_psi_c --do 
python -m experiments.exp_ir_study_base_psi_c1 --do 
python -m experiments.exp_ir_study_base_psi_p --do 
python -m experiments.exp_ir_study_base_psi_p1 --do 
