python exp_boltzmann.py --do
python exp_marketpower.py --do
python exp_preferential.py --do
python exp_restrictedmarket.py --do
python exp_shockedmarket.py --do
python exp_smallworld.py --do
python exp_surviving.4.200.py --do
python exp_surviving.4.py --do
python exp_surviving.10.py --do
