#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Plots:
 - Generate a table of axis_x x axis_y plots:

      columns are items of statistics of gdts generated by interbank.py
      rows are different experiments conducted

@author: hector@bith.net
@date:   10/2025
"""

import sys
import matplotlib.pyplot as plt
import numpy as np
import os
from interbank import Statistics


axis_x = ['equity', 'bankruptcies', 'interest_rate']
titles_x = ['$E$', 'bankruptcy', '$i_r$']
axis_y = ['1_psi0', '1_psi025', '1_psi05', '1_psi075', '1_psi1']  #, '3_psiendog']
titles_y = ['psi=0', 'psi=0.25', 'psi=0.5', 'psi=0.75', 'psi=0.99']  #,'psi endogenous' ]
output = 'psi_p.png'
title_of_output = 'comparing psi/p'

# x inside each individual plot (in this case, values of p):
x = list(np.linspace(0.0001, 0.2, num=5))

input_dir = '/experiments'
rows, cols = len(axis_y), len(axis_x)

plt.title(title_of_output)
fig, axes = plt.subplots(rows, cols, figsize=(12, 10))
for i, item_i in enumerate(axis_y):
    # load data:
    if not os.path.isdir(input_dir + '\\' + item_i):
        break
    data = Statistics.read_gdt(input_dir + '\\' + item_i + '\\results.gdt')
    yys = {}
    for j, item_j in enumerate(axis_x):

        y = data[item_j]
        yerr = data['std_' + item_j] / 2

        yys[item_j] = y

        # y = np.random.normal(10, 0.5, size=len(x)) + i + 0.3 * j
        # yerr = np.random.uniform(0.05, 0.15, size=len(x))

        # Plot line + error bars
        axes[i, j].errorbar(x, y, yerr=yerr, fmt='o-', color='black', ecolor='black',
                            capsize=3, elinewidth=1, markerfacecolor='none', markeredgecolor='black')

        # Remove grid and background
        axes[i, j].grid(False)
        axes[i, j].set_facecolor('white')
        # axes[i, j].set_title( 'a'+ ' '+ )

        # Optionally set axis labels
        if i == rows - 1:
            axes[i, j].set_xlabel(titles_x[j])
        if j == 0:
            axes[i, j].set_ylabel(titles_y[i])
    print("-----------", titles_y[i], "-----------")
    for k, value in enumerate(x):
        result = "p=%5.3f" % value
        result1 = "%-10s" % " "
        for item_j in axis_x:
            result += "%14.6f" % yys[item_j][k]
            result1 += "%-13s" % item_j
        print(result)

print(result1)
plt.tight_layout()
plt.savefig(output)
print("\n\n", output)
